### ISSUE TITLE
pip show doesn't provide proper git tag

### ISSUE THREAD

**Issue by xasima** [taigaio/taiga-contrib-gogs#13]
The command to svn-export of taiga-contrib-gogs  contains  `pip show taiga-contrib-gogs`. This doesn't return anything, if taiga repo is gust cloned. So it's needed to manually enter the latest tag.

**Comment by bameda** [comment]
if you clone the repo use `front/dist`

See `Dev Env` instructions in README.md

**Comment by bameda** [comment]
But be careful because if you clone the repo and use master brach you have to use taiga-back and taiga-front with the same branch and it's unstable.
