### ISSUE TITLE
API to get the payload URL and secret

### ISSUE THREAD

**Issue by rawlingsj** [taigaio/taiga-contrib-gogs#2]
Is there an API to get the gogs plugin payload URL and secret?  I've had a look and couldn't see any obvious way.

i.e. 

curl -H "Authorization: Bearer ${AUTH_TOKEN}" "https://localhost:8000/api/v1/gogs"

I'd like to automatically set up the webhooks in gogs when a new repo is created.

**Comment by bameda** [comment]
This plugins use the resource project-modules-configuration
- GET: http://taigaio.github.io/taiga-doc/dist/api.html#projects-get-modules
- PATCH: http://taigaio.github.io/taiga-doc/dist/api.html#projects-edit-modules

Try with:

```
curl -X GET \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer ${AUTH_TOKEN}" \
  https://localhost:8000/v1/projects/123/modules
```

and the call returm somethin like that:

```
{
    "gogs": {
        "secret": "b7a95570051a49ad8fb9482b5ef40262"
    }
}
```

The payload url is always the same:  `/api/v1/gogs-hook?project=<id>`

**Comment by rawlingsj** [comment]
Works perfectly - thanks!
