### ISSUE TITLE
Template failing to render

### ISSUE THREAD

**Issue by tonydspaniard** [taigaio/taiga-contrib-gogs#9]
Any idea why is this happening?

Thanks in advance 

![captura de pantalla 2015-09-27 a la s 11 54 52](https://cloud.githubusercontent.com/assets/566016/10122155/ad205a8c-650e-11e5-9f32-a62936e13145.png)

**Comment by bameda** [comment]
This is a problems between your taiga-front version and your plugin

**Comment by tonydspaniard** [comment]
@bameda installed taiga-vagrant + taiga-contrib-gogs 0.0.7

**Comment by bameda** [comment]
yep, but what is the version of your taiga-front instance, for example

```
bameda@cosmiclatte ~/k/p/2/t/taiga-front-dist> git describe --tags
1.8.0-8-g04d9abb
```
